# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18OULEdeRKc_vMarvOy96yhXAPsQV3Nh4
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    roc_curve
)

from sklearn.impute import SimpleImputer


from imblearn.over_sampling import SMOTE

# -----------------------------
# 1. LOAD DATA
# -----------------------------
df = pd.read_csv("application_train.csv")
print("Initial shape:", df.shape)

# -----------------------------
# 2. BUSINESS UNDERSTANDING
# -----------------------------
print(df["TARGET"].value_counts(normalize=True))

# -----------------------------
# 3. DROP ID COLUMN
# -----------------------------
df.drop(columns=["SK_ID_CURR"], inplace=True)

# -----------------------------
# 4. DROP HIGH MISSING COLUMNS
# -----------------------------
missing_pct = df.isnull().mean() * 100
drop_cols = missing_pct[missing_pct > 60].index
df.drop(columns=drop_cols, inplace=True)

print("Dropped columns:", len(drop_cols))
print("Shape after drop:", df.shape)

# -----------------------------
# 5. FEATURE ENGINEERING
# -----------------------------
df["DTI_RATIO"] = df["AMT_CREDIT"] / df["AMT_INCOME_TOTAL"]

df["AGE_YEARS"] = (-df["DAYS_BIRTH"] / 365).astype(int)

df["AGE_GROUP"] = pd.cut(
    df["AGE_YEARS"],
    bins=[20, 30, 40, 50, 60, 100],
    labels=["20-30", "30-40", "40-50", "50-60", "60+"]
)

# 🔴 VERY IMPORTANT FIX
df["AGE_GROUP"] = df["AGE_GROUP"].astype("object")

# -----------------------------
# 6. EDA
# -----------------------------
sns.countplot(x="TARGET", data=df)
plt.title("Class Distribution")
plt.show()

plt.figure(figsize=(10, 6))
sns.heatmap(df.select_dtypes(include=np.number).corr(), cmap="coolwarm")
plt.show()

# -----------------------------
# 7. SPLIT FEATURES & TARGET
# -----------------------------
X = df.drop("TARGET", axis=1)
y = df["TARGET"]

# -----------------------------
# 8. IDENTIFY COLUMN TYPES (FIXED)
# -----------------------------
cat_cols = X.select_dtypes(include=["object", "category"]).columns
num_cols = X.select_dtypes(exclude=["object", "category"]).columns

print("Categorical columns:", list(cat_cols))
print("Numerical columns:", list(num_cols))

# -----------------------------
# 9. PREPROCESSING PIPELINE
# -----------------------------
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, num_cols),
        ("cat", categorical_transformer, cat_cols)
    ]
)

# -----------------------------
# 10. TRAIN–TEST SPLIT
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# -----------------------------
# 11. SMOTE (IMBALANCED DATA)
# -----------------------------
X_train_processed = preprocessor.fit_transform(X_train)

smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train_processed, y_train)

# -----------------------------
# 12. LOGISTIC REGRESSION
# -----------------------------
log_model = LogisticRegression(max_iter=1000, class_weight="balanced")
log_model.fit(X_resampled, y_resampled)

y_pred_log = log_model.predict(preprocessor.transform(X_test))
y_prob_log = log_model.predict_proba(preprocessor.transform(X_test))[:, 1]

# -----------------------------
# 13. RANDOM FOREST
# -----------------------------
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

rf.fit(X_resampled, y_resampled)

y_pred_rf = rf.predict(preprocessor.transform(X_test))
y_prob_rf = rf.predict_proba(preprocessor.transform(X_test))[:, 1]

# -----------------------------
# 14. GRADIENT BOOSTING
# -----------------------------
gb = GradientBoostingClassifier()
gb.fit(X_resampled, y_resampled)

y_pred_gb = gb.predict(preprocessor.transform(X_test))
y_prob_gb = gb.predict_proba(preprocessor.transform(X_test))[:, 1]

# -----------------------------
# 15. EVALUATION FUNCTION
# -----------------------------
def evaluate(name, y_test, y_pred, y_prob):
    print(f"\n{name}")
    print("Accuracy :", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall   :", recall_score(y_test, y_pred))
    print("F1 Score :", f1_score(y_test, y_pred))
    print("ROC-AUC  :", roc_auc_score(y_test, y_prob))


evaluate("Logistic Regression", y_test, y_pred_log, y_prob_log)
evaluate("Random Forest", y_test, y_pred_rf, y_prob_rf)
evaluate("Gradient Boosting", y_test, y_pred_gb, y_prob_gb)

# -----------------------------
# 16. CONFUSION MATRIX
# -----------------------------
cm = confusion_matrix(y_test, y_pred_rf)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Random Forest")
plt.show()

# -----------------------------
# 17. ROC CURVE
# -----------------------------
fpr, tpr, _ = roc_curve(y_test, y_prob_rf)
plt.plot(fpr, tpr, label="Random Forest")
plt.plot([0, 1], [0, 1], "--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.title("ROC Curve")
plt.show()

import joblib

joblib.dump(rf, "credit_risk_model.pkl")
joblib.dump(preprocessor, "preprocessor.pkl")

print("Model and preprocessor saved")





