# -*- coding: utf-8 -*-
"""enginow-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18XLFJLNr6PSz9kss8VXmOuqdjm0FD2Sm
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix, roc_curve
)

from imblearn.over_sampling import SMOTE

df = pd.read_csv("Telco_Cusomer_Churn.csv")
df.head()

df.drop('customerID', axis=1, inplace=True)


df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')


df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)


df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

df['AvgRevenue'] = df['TotalCharges'] / (df['tenure'] + 1)


df['TenureGroup'] = pd.cut(
    df['tenure'],
    bins=[0, 12, 36, 72],
    labels=['New', 'Mid', 'Loyal']
).astype(str)

services = [
    'OnlineSecurity','OnlineBackup','DeviceProtection',
    'TechSupport','StreamingTV','StreamingMovies'
]

df['ServiceCount'] = df[services].apply(lambda x: (x == 'Yes').sum(), axis=1)


df['ContractRisk'] = df['Contract'].map({
    'Month-to-month': 3,
    'One year': 2,
    'Two year': 1
})

sns.countplot(x='Churn', data=df)
plt.title("Churn Distribution")
plt.show()

sns.countplot(x='Contract', hue='Churn', data=df)
plt.title("Churn by Contract Type")
plt.xticks(rotation=30)
plt.show()

sns.histplot(data=df, x='MonthlyCharges', hue='Churn', kde=True)
plt.title("Monthly Charges vs Churn")
plt.show()

X = df.drop('Churn', axis=1)
y = df['Churn']


cat_cols = X.select_dtypes(include='object').columns
num_cols = X.select_dtypes(exclude='object').columns


preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ]
)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


X_train_pre = preprocessor.fit_transform(X_train)
X_test_pre = preprocessor.transform(X_test)


smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train_pre, y_train)

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_sm, y_train_sm)

rf = RandomForestClassifier(n_estimators=200, random_state=42)
rf.fit(X_train_sm, y_train_sm)

gb = GradientBoostingClassifier()
gb.fit(X_train_sm, y_train_sm)

def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:,1]

    return {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred),
        "ROC_AUC": roc_auc_score(y_test, y_prob)
    }

results = pd.DataFrame({
    "Logistic Regression": evaluate_model(lr, X_test_pre, y_test),
    "Random Forest": evaluate_model(rf, X_test_pre, y_test),
    "Gradient Boosting": evaluate_model(gb, X_test_pre, y_test)
})

results

cm = confusion_matrix(y_test, rf.predict(X_test_pre))
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix - Random Forest")
plt.show()

importances = rf.feature_importances_
feature_names = preprocessor.get_feature_names_out()

feat_imp = pd.Series(importances, index=feature_names).sort_values(ascending=False)[:10]
feat_imp.plot(kind='barh')
plt.title("Top Churn Drivers")
plt.show()

import pickle

# Save model
with open("churn_model.pkl", "wb") as f:
    pickle.dump(rf, f)

# Save preprocessor
with open("preprocessor.pkl", "wb") as f:
    pickle.dump(preprocessor, f)

